# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.provision "shell", path: "vagrant-init.sh"
  config.vm.network "forwarded_port", guest: 5432, host: 35432
  config.vm.box = "u15pg94"
  config.vm.box_url = "https://github.com/mhuckaby/vagrantboxes/releases/download/u15pg94/u15pg94.box"

end

